# Generated by Django 4.0.4 on 2022-05-23 09:25

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension ##


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        TrigramExtension(), ##
        
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LettersToNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.CharField(max_length=50000)),
                ('number', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50000, unique=True)),
                ('price', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=20, unique=True)),
                ('count', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(blank=True, max_length=50000)),
                ('response', models.CharField(blank=True, max_length=50000)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.intent', to_field='title')),
                ('previous_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_chats', to='core.intent', to_field='title')),
            ],
        ),
    ]
