# Generated by Django 4.0.4 on 2022-05-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
